import { useState, useEffect } from 'react'
import axios from 'axios'
import { useNavigate, Link } from 'react-router-dom'
import jsPDF from 'jspdf'

const API = import.meta.env.VITE_API_URL

export default function Analyze() {
    const [resumes, setResumes] = useState([])
    const [resumeId, setResumeId] = useState('')
    const [jobDescription, setJobDescription] = useState('')
    const [result, setResult] = useState(null)
    const [loading, setLoading] = useState(false)
    const navigate = useNavigate()
    const token = localStorage.getItem('token')

    useEffect(() => {
        if (!token) { navigate('/login'); return }
        axios.get(`${API}/api/resume/list`, {
            headers: { Authorization: `Bearer ${token}` }
        }).then(res => setResumes(res.data))
    }, [])

    const handleAnalyze = async () => {
        if (!resumeId || !jobDescription) { alert('Select resume and enter job description'); return }
        setLoading(true)
        try {
            const res = await axios.post(
                `${API}/api/analysis/analyze?resumeId=${resumeId}&jobDescription=${encodeURIComponent(jobDescription)}`,
                {},
                { headers: { Authorization: `Bearer ${token}` } }
            )
            setResult(res.data)
        } catch (e) {
            alert('Analysis failed')
        }
        setLoading(false)
    }

    const downloadPDF = () => {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        let y = 20

        // Title
        doc.setFontSize(22)
        doc.setTextColor(168, 85, 247)
        doc.text('ResuMatch Analysis Report', pageWidth / 2, y, { align: 'center' })
        y += 10

        // Divider
        doc.setDrawColor(168, 85, 247)
        doc.line(20, y, pageWidth - 20, y)
        y += 10

        // Job Title & Industry
        doc.setFontSize(13)
        doc.setTextColor(50, 50, 50)
        doc.text(`Job Title: ${result.jobTitle}`, 20, y)
        y += 8
        doc.text(`Industry: ${result.industry}`, 20, y)
        y += 12

        // Scores
        doc.setFontSize(14)
        doc.setTextColor(168, 85, 247)
        doc.text(`Match Score: ${result.matchPercentage}%`, 20, y)
        y += 8
        doc.setTextColor(34, 197, 94)
        doc.text(`ATS Score: ${result.atsScore}%`, 20, y)
        y += 12

        // Sections
        const sections = [
            { label: 'Matched Keywords', value: result.matchedKeywords, color: [34, 197, 94] },
            { label: 'Missing Keywords', value: result.missingKeywords, color: [239, 68, 68] },
            { label: 'Suggestions', value: result.suggestions, color: [50, 50, 50] },
            { label: 'Improvement Tips', value: result.improvementTips, color: [50, 50, 50] },
            { label: 'Skills Gap', value: result.skillsGap, color: [234, 179, 8] },
            { label: 'Experience Gap', value: result.experienceGap, color: [234, 179, 8] },
        ]

        sections.forEach(section => {
            doc.setFontSize(12)
            doc.setTextColor(100, 100, 100)
            doc.text(`${section.label}:`, 20, y)
            y += 7
            doc.setFontSize(11)
            doc.setTextColor(...section.color)
            const lines = doc.splitTextToSize(section.value || 'N/A', pageWidth - 40)
            doc.text(lines, 20, y)
            y += lines.length * 6 + 6

            if (y > 270) {
                doc.addPage()
                y = 20
            }
        })

        // Footer
        doc.setFontSize(9)
        doc.setTextColor(150, 150, 150)
        doc.text(`Generated by ResuMatch • ${new Date().toLocaleDateString()}`, pageWidth / 2, 290, { align: 'center' })

        doc.save(`ResuMatch_Report_${result.jobTitle || 'Analysis'}.pdf`)
    }

    return (
        <div className="min-h-screen bg-gray-950 text-white p-8">
            <div className="max-w-3xl mx-auto">
                <div className="flex justify-between items-center mb-8">
                    <h2 className="text-2xl font-bold">Analyze Resume</h2>
                    <Link to="/dashboard" className="text-gray-400 hover:text-white">← Dashboard</Link>
                </div>
                <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800 mb-6">
                    <label className="text-gray-400 block mb-2">Select Resume</label>
                    <select value={resumeId} onChange={e => setResumeId(e.target.value)} className="w-full bg-gray-800 text-white p-3 rounded-lg mb-4 outline-none">
                        <option value="">-- Select --</option>
                        {resumes.map(r => <option key={r.id} value={r.id}>{r.fileName} (v{r.versionNumber})</option>)}
                    </select>
                    <label className="text-gray-400 block mb-2">Job Description</label>
                    <textarea value={jobDescription} onChange={e => setJobDescription(e.target.value)} rows={5} className="w-full bg-gray-800 text-white p-3 rounded-lg outline-none" placeholder="Paste job description here..." />
                    <button onClick={handleAnalyze} disabled={loading} className="w-full bg-purple-600 hover:bg-purple-700 text-white p-3 rounded-lg font-semibold mt-4 disabled:opacity-50">
                        {loading ? 'Analyzing...' : 'Analyze'}
                    </button>
                </div>

                {result && (
                    <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-xl font-bold">Results</h3>
                            <button onClick={downloadPDF} className="bg-purple-600 hover:bg-purple-700 px-4 py-2 rounded-lg text-sm font-semibold">
                                Download PDF
                            </button>
                        </div>
                        <div className="grid grid-cols-2 gap-4 mb-4">
                            <div className="bg-gray-800 p-4 rounded-xl text-center">
                                <p className="text-gray-400 text-sm">Match Score</p>
                                <p className="text-4xl font-bold text-purple-400">{result.matchPercentage}%</p>
                            </div>
                            <div className="bg-gray-800 p-4 rounded-xl text-center">
                                <p className="text-gray-400 text-sm">ATS Score</p>
                                <p className="text-4xl font-bold text-green-400">{result.atsScore}%</p>
                            </div>
                        </div>
                        <div className="mb-3">
                            <p className="text-gray-400 text-sm mb-1">Matched Keywords</p>
                            <p className="text-green-400">{result.matchedKeywords}</p>
                        </div>
                        <div className="mb-3">
                            <p className="text-gray-400 text-sm mb-1">Missing Keywords</p>
                            <p className="text-red-400">{result.missingKeywords}</p>
                        </div>
                        <div className="mb-3">
                            <p className="text-gray-400 text-sm mb-1">Suggestions</p>
                            <p className="text-gray-300">{result.suggestions}</p>
                        </div>
                        <div className="mb-3">
                            <p className="text-gray-400 text-sm mb-1">Improvement Tips</p>
                            <p className="text-gray-300">{result.improvementTips}</p>
                        </div>
                        <div className="mb-3">
                            <p className="text-gray-400 text-sm mb-1">Skills Gap</p>
                            <p className="text-yellow-400">{result.skillsGap}</p>
                        </div>
                        <div>
                            <p className="text-gray-400 text-sm mb-1">Experience Gap</p>
                            <p className="text-yellow-400">{result.experienceGap}</p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    )
}