import { useState, useEffect } from 'react'
import axios from 'axios'
import { useNavigate, Link } from 'react-router-dom'
import jsPDF from 'jspdf'

const API = import.meta.env.VITE_API_URL

export default function CoverLetter() {
    const [resumes, setResumes] = useState([])
    const [resumeId, setResumeId] = useState('')
    const [jobDescription, setJobDescription] = useState('')
    const [companyName, setCompanyName] = useState('')
    const [jobTitle, setJobTitle] = useState('')
    const [coverLetter, setCoverLetter] = useState('')
    const [loading, setLoading] = useState(false)
    const navigate = useNavigate()
    const token = localStorage.getItem('token')

    useEffect(() => {
        if (!token) { navigate('/login'); return }
        axios.get(`${API}/api/resume/list`, {
            headers: { Authorization: `Bearer ${token}` }
        }).then(res => setResumes(res.data))
    }, [])

    const handleGenerate = async () => {
        if (!resumeId || !jobDescription || !companyName || !jobTitle) {
            alert('Please fill all fields')
            return
        }
        setLoading(true)
        try {
            const res = await axios.post(
                `${API}/api/cover-letter/generate`,
                { resumeId, jobDescription, companyName, jobTitle },
                { headers: { Authorization: `Bearer ${token}` } }
            )
            setCoverLetter(res.data.coverLetter)
        } catch (e) {
            alert('Generation failed')
        }
        setLoading(false)
    }

    const downloadPDF = () => {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        let y = 20

        doc.setFontSize(18)
        doc.setTextColor(168, 85, 247)
        doc.text('Cover Letter', pageWidth / 2, y, { align: 'center' })
        y += 10

        doc.setDrawColor(168, 85, 247)
        doc.line(20, y, pageWidth - 20, y)
        y += 10

        doc.setFontSize(11)
        doc.setTextColor(50, 50, 50)
        const lines = doc.splitTextToSize(coverLetter, pageWidth - 40)
        lines.forEach(line => {
            if (y > 270) { doc.addPage(); y = 20 }
            doc.text(line, 20, y)
            y += 7
        })

        doc.setFontSize(9)
        doc.setTextColor(150, 150, 150)
        doc.text(`Generated by ResuMatch • ${new Date().toLocaleDateString()}`, pageWidth / 2, 290, { align: 'center' })

        doc.save(`CoverLetter_${companyName}_${jobTitle}.pdf`)
    }

    return (
        <div className="min-h-screen bg-gray-950 text-white p-8">
            <div className="max-w-3xl mx-auto">
                <div className="flex justify-between items-center mb-8">
                    <h2 className="text-2xl font-bold">Cover Letter Generator</h2>
                    <Link to="/dashboard" className="text-gray-400 hover:text-white">← Dashboard</Link>
                </div>

                <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800 mb-6">
                    <label className="text-gray-400 block mb-2">Select Resume</label>
                    <select value={resumeId} onChange={e => setResumeId(e.target.value)}
                            className="w-full bg-gray-800 text-white p-3 rounded-lg mb-4 outline-none">
                        <option value="">-- Select --</option>
                        {resumes.map(r => <option key={r.id} value={r.id}>{r.fileName} (v{r.versionNumber})</option>)}
                    </select>

                    <label className="text-gray-400 block mb-2">Company Name</label>
                    <input value={companyName} onChange={e => setCompanyName(e.target.value)}
                           className="w-full bg-gray-800 text-white p-3 rounded-lg mb-4 outline-none"
                           placeholder="e.g. Google" />

                    <label className="text-gray-400 block mb-2">Job Title</label>
                    <input value={jobTitle} onChange={e => setJobTitle(e.target.value)}
                           className="w-full bg-gray-800 text-white p-3 rounded-lg mb-4 outline-none"
                           placeholder="e.g. Software Engineer" />

                    <label className="text-gray-400 block mb-2">Job Description</label>
                    <textarea value={jobDescription} onChange={e => setJobDescription(e.target.value)}
                              rows={5} className="w-full bg-gray-800 text-white p-3 rounded-lg outline-none"
                              placeholder="Paste job description here..." />

                    <button onClick={handleGenerate} disabled={loading}
                            className="w-full bg-purple-600 hover:bg-purple-700 text-white p-3 rounded-lg font-semibold mt-4 disabled:opacity-50">
                        {loading ? 'Generating...' : 'Generate Cover Letter'}
                    </button>
                </div>

                {coverLetter && (
                    <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-xl font-bold">Your Cover Letter</h3>
                            <button onClick={downloadPDF}
                                    className="bg-purple-600 hover:bg-purple-700 px-4 py-2 rounded-lg text-sm font-semibold">
                                Download PDF
                            </button>
                        </div>
                        <textarea
                            value={coverLetter}
                            onChange={e => setCoverLetter(e.target.value)}
                            rows={15}
                            className="w-full bg-gray-800 text-white p-4 rounded-lg outline-none resize-none text-sm leading-relaxed"
                        />
                        <p className="text-gray-500 text-xs mt-2">You can edit the cover letter before downloading.</p>
                    </div>
                )}
            </div>
        </div>
    )
}