import { useState, useEffect } from 'react'
import axios from 'axios'
import { useNavigate, Link } from 'react-router-dom'
import jsPDF from 'jspdf'

const API = import.meta.env.VITE_API_URL

export default function CoverLetter() {
    const [resumes, setResumes]           = useState([])
    const [resumeId, setResumeId]         = useState('')
    const [jobDescription, setJobDesc]    = useState('')
    const [companyName, setCompanyName]   = useState('')
    const [jobTitle, setJobTitle]         = useState('')
    const [coverLetter, setCoverLetter]   = useState('')
    const [loading, setLoading]           = useState(false)
    const [wordCount, setWordCount]       = useState(0)
    const [stage, setStage]               = useState(0)
    const navigate = useNavigate()
    const token    = localStorage.getItem('token')

    const stages = ['Reading your resume...', 'Analyzing job requirements...', 'Crafting your letter...', 'Polishing the text...']

    useEffect(() => {
        if (!token) { navigate('/login'); return }
        axios.get(`${API}/api/resume/list`, { headers: { Authorization: `Bearer ${token}` } })
            .then(res => setResumes(res.data))
    }, [])

    useEffect(() => {
        if (!loading) { setStage(0); return }
        const t = setInterval(() => setStage(s => (s+1) % stages.length), 1200)
        return () => clearInterval(t)
    }, [loading])

    useEffect(() => {
        setWordCount(coverLetter.trim().split(/\s+/).filter(Boolean).length)
    }, [coverLetter])

    const handleGenerate = async () => {
        if (!resumeId || !jobDescription || !companyName || !jobTitle) {
            alert('Please fill all fields'); return
        }
        setLoading(true); setCoverLetter('')
        try {
            const res = await axios.post(
                `${API}/api/cover-letter/generate`,
                { resumeId, jobDescription, companyName, jobTitle },
                { headers: { Authorization: `Bearer ${token}` } }
            )
            setCoverLetter(res.data.coverLetter)
        } catch { alert('Generation failed') }
        setLoading(false)
    }

    const downloadPDF = () => {
        const doc = new jsPDF(); const W = doc.internal.pageSize.getWidth(); let y = 20
        doc.setFontSize(18); doc.setTextColor(139,92,246)
        doc.text('Cover Letter', W/2, y, { align:'center' }); y += 6
        doc.setFontSize(11); doc.setTextColor(120,120,140)
        doc.text(`${jobTitle} at ${companyName}`, W/2, y+6, { align:'center' }); y += 14
        doc.setDrawColor(139,92,246); doc.line(20, y, W-20, y); y += 10
        doc.setFontSize(11); doc.setTextColor(50,50,50)
        doc.splitTextToSize(coverLetter, W-40).forEach(line => {
            if (y > 270) { doc.addPage(); y = 20 }
            doc.text(line, 20, y); y += 7
        })
        doc.setFontSize(9); doc.setTextColor(150,150,150)
        doc.text(`Generated by ResuMatch • ${new Date().toLocaleDateString()}`, W/2, 290, { align:'center' })
        doc.save(`CoverLetter_${companyName}_${jobTitle}.pdf`)
    }

    const copyToClipboard = () => {
        navigator.clipboard.writeText(coverLetter)
    }

    return (
        <div className="page" style={{ minHeight:'100vh', padding:'40px' }}>
            <div className="bg-grid" /><div className="orb orb-1" /><div className="orb orb-2" />

            <div style={{ maxWidth:'860px', margin:'0 auto', position:'relative', zIndex:1 }}>
                {/* header */}
                <div className="page-enter" style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'36px' }}>
                    <div>
                        <div className="section-label">AI Writing Assistant</div>
                        <h2 style={{ fontFamily:'var(--font-display)', fontWeight:800, fontSize:'28px' }}>Cover Letter Generator</h2>
                    </div>
                    <Link to="/dashboard" className="btn-ghost">← Dashboard</Link>
                </div>

                <div style={{ display:'grid', gridTemplateColumns: coverLetter ? '1fr 1fr' : '1fr', gap:'24px', alignItems:'start' }}>
                    {/* ── INPUT FORM ── */}
                    <div className="glass page-enter" style={{ padding:'32px', animationDelay:'0.1s' }}>
                        <div className="section-label" style={{ marginBottom:'20px' }}>Job Details</div>

                        <div style={{ display:'flex', flexDirection:'column', gap:'16px' }}>
                            <div>
                                <div className="section-label">Resume</div>
                                <select value={resumeId} onChange={e => setResumeId(e.target.value)} className="input-field" style={{ cursor:'pointer' }}>
                                    <option value="">— Choose resume —</option>
                                    {resumes.map(r => <option key={r.id} value={r.id}>{r.fileName} (v{r.versionNumber})</option>)}
                                </select>
                            </div>

                            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'12px' }}>
                                <div>
                                    <div className="section-label">Company</div>
                                    <input className="input-field" placeholder="e.g. Google" value={companyName} onChange={e => setCompanyName(e.target.value)} />
                                </div>
                                <div>
                                    <div className="section-label">Job Title</div>
                                    <input className="input-field" placeholder="e.g. SWE" value={jobTitle} onChange={e => setJobTitle(e.target.value)} />
                                </div>
                            </div>

                            <div>
                                <div className="section-label">Job Description</div>
                                <textarea
                                    value={jobDescription}
                                    onChange={e => setJobDesc(e.target.value)}
                                    rows={coverLetter ? 7 : 8}
                                    className="input-field"
                                    placeholder="Paste the job description..."
                                    style={{ resize:'vertical' }}
                                />
                            </div>
                        </div>

                        <button className="btn-primary" onClick={handleGenerate} disabled={loading} style={{ width:'100%', justifyContent:'center', padding:'14px', fontSize:'14px', marginTop:'20px' }}>
                            {loading
                                ? <><span className="spinner" style={{ width:'16px', height:'16px', borderWidth:'2px' }} /> {stages[stage]}</>
                                : <><span>✉</span> Generate Cover Letter</>
                            }
                        </button>

                        {/* tips */}
                        <div style={{ marginTop:'20px', background:'rgba(139,92,246,0.04)', border:'1px solid rgba(139,92,246,0.1)', borderRadius:'12px', padding:'14px 16px' }}>
                            <div className="section-label" style={{ marginBottom:'8px', color:'var(--purple)' }}>💡 Tips</div>
                            {['Use a detailed job description for best results', 'You can edit the letter after generation', 'Include specific company details'].map((tip, i) => (
                                <p key={i} style={{ color:'var(--text-3)', fontSize:'12px', marginBottom:'4px' }}>· {tip}</p>
                            ))}
                        </div>
                    </div>

                    {/* ── OUTPUT ── */}
                    {coverLetter && (
                        <div className="glass page-enter" style={{ padding:'32px' }}>
                            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'20px', flexWrap:'wrap', gap:'10px' }}>
                                <div>
                                    <div className="section-label">Generated Letter</div>
                                    <h3 style={{ fontFamily:'var(--font-display)', fontWeight:700, fontSize:'16px' }}>
                                        {jobTitle} at {companyName}
                                    </h3>
                                </div>
                                <div style={{ display:'flex', gap:'8px' }}>
                                    <button onClick={copyToClipboard} className="btn-ghost" style={{ fontSize:'12px', padding:'7px 12px' }}>⎘ Copy</button>
                                    <button onClick={downloadPDF}     className="btn-primary" style={{ fontSize:'12px', padding:'7px 14px' }}>↓ PDF</button>
                                </div>
                            </div>

                            {/* word count */}
                            <div style={{ display:'flex', gap:'16px', marginBottom:'12px' }}>
                                <span style={{ fontSize:'11px', color:'var(--text-3)', fontFamily:'var(--font-mono)' }}>{wordCount} words</span>
                                <span style={{ fontSize:'11px', color:'var(--text-3)', fontFamily:'var(--font-mono)' }}>{coverLetter.length} chars</span>
                                <span style={{ fontSize:'11px', color:'var(--green)', fontFamily:'var(--font-mono)' }}>✓ AI-generated</span>
                            </div>

                            <textarea
                                value={coverLetter}
                                onChange={e => setCoverLetter(e.target.value)}
                                rows={22}
                                className="input-field"
                                style={{ resize:'none', fontSize:'13px', lineHeight:1.8, fontFamily:'var(--font-body)' }}
                            />
                            <p style={{ color:'var(--text-3)', fontSize:'11px', marginTop:'8px', fontFamily:'var(--font-mono)' }}>
                                // click to edit before downloading
                            </p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}